name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "include/**"
      - "src/**"
      - "tools/**"
      - "third_party/**"
      - "CMakeLists.txt"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "include/**"
      - "src/**"
      - "tools/**"
      - "third_party/**"
      - "CMakeLists.txt"
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install dependencies
        run: just setup-deps-ubuntu

      - name: Build Video2X
        run: just build_type=Debug build

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: video2x-nightly-linux-amd64
          path: build/video2x-install

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools, SPIRV-Headers
          vulkan-use-cache: true

      - name: Install dependencies
        shell: pwsh
        run: |
          just setup-ffmpeg
          just setup-ncnn

      - name: Build Video2X
        shell: pwsh
        run: just build_type=Debug build

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: video2x-nightly-windows-amd64
          path: build/video2x-install

  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build the Docker image
        with:
          registry: ghcr.io
          dockerfile: packaging/docker/Dockerfile
          image: video2x
          tags: latest
          pushImage: false

  appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: just setup-deps-appimage

      - name: Build AppImage
        run: just prune_rife_models=false build-appimage

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Video2X-x86_64.AppImage
          path: Video2X-x86_64.AppImage
