name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: echo version=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

  ubuntu-2404:
    name: Build Ubuntu 24.04 release
    needs:
      - setup
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install dependencies
        run: just setup-deps-ubuntu

      - name: Build Video2X
        run: just build-ubuntu2404-deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: video2x-linux-ubuntu-2404-amd64
          path: build/video2x-linux-ubuntu-amd64.deb

  windows:
    name: Build Windows release
    needs:
      - setup
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools, SPIRV-Headers
          vulkan-use-cache: true

      - name: Install dependencies
        shell: pwsh
        run: |
          just setup-ffmpeg
          just setup-ncnn

      - name: Build Video2X
        shell: pwsh
        run: just build

      - name: Compress artifacts
        shell: pwsh
        run: Compress-Archive -Path build/video2x-install/* -DestinationPath build/video2x-windows-amd64.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: video2x-windows-amd64
          path: build/video2x-windows-amd64.zip

  appimage:
    name: Build AppImage release
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: just setup-deps-appimage

      - name: Build AppImage
        run: just appimage

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Video2X-x86_64.AppImage
          path: Video2X-x86_64.AppImage

  container:
    name: Build and upload container
    # Disabled
    if: false
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push the Docker image
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: packaging/docker/Dockerfile
          image: video2x
          tags: latest, ${{ needs.setup.outputs.version }}

  create-release:
    name: Create release
    needs:
      - setup
      - ubuntu-2404
      - windows
      - appimage
      # - container
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.setup.outputs.version }}
          name: ${{ needs.setup.outputs.version }}
          draft: true
          prerelease: false
          files: |
            video2x-linux-ubuntu-2404-amd64/video2x-linux-ubuntu-amd64.deb
            video2x-windows-amd64/video2x-windows-amd64.zip
            Video2X-x86_64.AppImage/Video2X-x86_64.AppImage
